#include <iostream>
#include "wrapper.hpp"

void Rust_CThostFtdcTraderSpi::OnFrontConnected() { return Rust_CThostFtdcTraderSpi_Trait_OnFrontConnected(m_rust); }
void Rust_CThostFtdcTraderSpi::OnFrontDisconnected(int nReason) { return Rust_CThostFtdcTraderSpi_Trait_OnFrontDisconnected(m_rust, nReason); }
void Rust_CThostFtdcTraderSpi::OnHeartBeatWarning(int nTimeLapse) { return Rust_CThostFtdcTraderSpi_Trait_OnHeartBeatWarning(m_rust, nTimeLapse); }
void Rust_CThostFtdcTraderSpi::OnRspAuthenticate(CThostFtdcRspAuthenticateField* pRspAuthenticateField, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspAuthenticate(m_rust, pRspAuthenticateField, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspUserLogin(CThostFtdcRspUserLoginField* pRspUserLogin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspUserLogin(m_rust, pRspUserLogin, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspUserLogout(CThostFtdcUserLogoutField* pUserLogout, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspUserLogout(m_rust, pUserLogout, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspUserPasswordUpdate(CThostFtdcUserPasswordUpdateField* pUserPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspUserPasswordUpdate(m_rust, pUserPasswordUpdate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspTradingAccountPasswordUpdate(CThostFtdcTradingAccountPasswordUpdateField* pTradingAccountPasswordUpdate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspTradingAccountPasswordUpdate(m_rust, pTradingAccountPasswordUpdate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspUserAuthMethod(CThostFtdcRspUserAuthMethodField* pRspUserAuthMethod, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspUserAuthMethod(m_rust, pRspUserAuthMethod, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspGenUserCaptcha(CThostFtdcRspGenUserCaptchaField* pRspGenUserCaptcha, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspGenUserCaptcha(m_rust, pRspGenUserCaptcha, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspGenUserText(CThostFtdcRspGenUserTextField* pRspGenUserText, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspGenUserText(m_rust, pRspGenUserText, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspOrderInsert(m_rust, pInputOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspParkedOrderInsert(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspParkedOrderInsert(m_rust, pParkedOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspParkedOrderAction(m_rust, pParkedOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspOrderAction(CThostFtdcInputOrderActionField* pInputOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspOrderAction(m_rust, pInputOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQueryMaxOrderVolume(CThostFtdcQueryMaxOrderVolumeField* pQueryMaxOrderVolume, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQueryMaxOrderVolume(m_rust, pQueryMaxOrderVolume, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspSettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspSettlementInfoConfirm(m_rust, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspRemoveParkedOrder(CThostFtdcRemoveParkedOrderField* pRemoveParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspRemoveParkedOrder(m_rust, pRemoveParkedOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspRemoveParkedOrderAction(CThostFtdcRemoveParkedOrderActionField* pRemoveParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspRemoveParkedOrderAction(m_rust, pRemoveParkedOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspExecOrderInsert(m_rust, pInputExecOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspExecOrderAction(CThostFtdcInputExecOrderActionField* pInputExecOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspExecOrderAction(m_rust, pInputExecOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspForQuoteInsert(m_rust, pInputForQuote, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQuoteInsert(m_rust, pInputQuote, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQuoteAction(CThostFtdcInputQuoteActionField* pInputQuoteAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQuoteAction(m_rust, pInputQuoteAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspBatchOrderAction(CThostFtdcInputBatchOrderActionField* pInputBatchOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspBatchOrderAction(m_rust, pInputBatchOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspOptionSelfCloseInsert(m_rust, pInputOptionSelfClose, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspOptionSelfCloseAction(CThostFtdcInputOptionSelfCloseActionField* pInputOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspOptionSelfCloseAction(m_rust, pInputOptionSelfCloseAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspCombActionInsert(m_rust, pInputCombAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryOrder(CThostFtdcOrderField* pOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryOrder(m_rust, pOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTrade(CThostFtdcTradeField* pTrade, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTrade(m_rust, pTrade, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestorPosition(CThostFtdcInvestorPositionField* pInvestorPosition, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestorPosition(m_rust, pInvestorPosition, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTradingAccount(m_rust, pTradingAccount, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestor(CThostFtdcInvestorField* pInvestor, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestor(m_rust, pInvestor, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTradingCode(CThostFtdcTradingCodeField* pTradingCode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTradingCode(m_rust, pTradingCode, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInstrumentMarginRate(CThostFtdcInstrumentMarginRateField* pInstrumentMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInstrumentMarginRate(m_rust, pInstrumentMarginRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInstrumentCommissionRate(CThostFtdcInstrumentCommissionRateField* pInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInstrumentCommissionRate(m_rust, pInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryExchange(CThostFtdcExchangeField* pExchange, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryExchange(m_rust, pExchange, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryProduct(CThostFtdcProductField* pProduct, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryProduct(m_rust, pProduct, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInstrument(CThostFtdcInstrumentField* pInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInstrument(m_rust, pInstrument, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryDepthMarketData(CThostFtdcDepthMarketDataField* pDepthMarketData, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryDepthMarketData(m_rust, pDepthMarketData, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySettlementInfo(CThostFtdcSettlementInfoField* pSettlementInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySettlementInfo(m_rust, pSettlementInfo, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTransferBank(CThostFtdcTransferBankField* pTransferBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTransferBank(m_rust, pTransferBank, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestorPositionDetail(CThostFtdcInvestorPositionDetailField* pInvestorPositionDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestorPositionDetail(m_rust, pInvestorPositionDetail, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryNotice(CThostFtdcNoticeField* pNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryNotice(m_rust, pNotice, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySettlementInfoConfirm(CThostFtdcSettlementInfoConfirmField* pSettlementInfoConfirm, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySettlementInfoConfirm(m_rust, pSettlementInfoConfirm, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestorPositionCombineDetail(CThostFtdcInvestorPositionCombineDetailField* pInvestorPositionCombineDetail, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestorPositionCombineDetail(m_rust, pInvestorPositionCombineDetail, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryCFMMCTradingAccountKey(CThostFtdcCFMMCTradingAccountKeyField* pCFMMCTradingAccountKey, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryCFMMCTradingAccountKey(m_rust, pCFMMCTradingAccountKey, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryEWarrantOffset(CThostFtdcEWarrantOffsetField* pEWarrantOffset, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryEWarrantOffset(m_rust, pEWarrantOffset, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestorProductGroupMargin(CThostFtdcInvestorProductGroupMarginField* pInvestorProductGroupMargin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestorProductGroupMargin(m_rust, pInvestorProductGroupMargin, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryExchangeMarginRate(CThostFtdcExchangeMarginRateField* pExchangeMarginRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryExchangeMarginRate(m_rust, pExchangeMarginRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryExchangeMarginRateAdjust(CThostFtdcExchangeMarginRateAdjustField* pExchangeMarginRateAdjust, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryExchangeMarginRateAdjust(m_rust, pExchangeMarginRateAdjust, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryExchangeRate(CThostFtdcExchangeRateField* pExchangeRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryExchangeRate(m_rust, pExchangeRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySecAgentACIDMap(CThostFtdcSecAgentACIDMapField* pSecAgentACIDMap, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySecAgentACIDMap(m_rust, pSecAgentACIDMap, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryProductExchRate(CThostFtdcProductExchRateField* pProductExchRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryProductExchRate(m_rust, pProductExchRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryProductGroup(CThostFtdcProductGroupField* pProductGroup, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryProductGroup(m_rust, pProductGroup, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryMMInstrumentCommissionRate(CThostFtdcMMInstrumentCommissionRateField* pMMInstrumentCommissionRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryMMInstrumentCommissionRate(m_rust, pMMInstrumentCommissionRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryMMOptionInstrCommRate(CThostFtdcMMOptionInstrCommRateField* pMMOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryMMOptionInstrCommRate(m_rust, pMMOptionInstrCommRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInstrumentOrderCommRate(CThostFtdcInstrumentOrderCommRateField* pInstrumentOrderCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInstrumentOrderCommRate(m_rust, pInstrumentOrderCommRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySecAgentTradingAccount(CThostFtdcTradingAccountField* pTradingAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySecAgentTradingAccount(m_rust, pTradingAccount, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySecAgentCheckMode(CThostFtdcSecAgentCheckModeField* pSecAgentCheckMode, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySecAgentCheckMode(m_rust, pSecAgentCheckMode, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQrySecAgentTradeInfo(CThostFtdcSecAgentTradeInfoField* pSecAgentTradeInfo, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQrySecAgentTradeInfo(m_rust, pSecAgentTradeInfo, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryOptionInstrTradeCost(CThostFtdcOptionInstrTradeCostField* pOptionInstrTradeCost, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryOptionInstrTradeCost(m_rust, pOptionInstrTradeCost, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryOptionInstrCommRate(CThostFtdcOptionInstrCommRateField* pOptionInstrCommRate, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryOptionInstrCommRate(m_rust, pOptionInstrCommRate, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryExecOrder(CThostFtdcExecOrderField* pExecOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryExecOrder(m_rust, pExecOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryForQuote(CThostFtdcForQuoteField* pForQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryForQuote(m_rust, pForQuote, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryQuote(CThostFtdcQuoteField* pQuote, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryQuote(m_rust, pQuote, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryOptionSelfClose(m_rust, pOptionSelfClose, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryInvestUnit(CThostFtdcInvestUnitField* pInvestUnit, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryInvestUnit(m_rust, pInvestUnit, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryCombInstrumentGuard(CThostFtdcCombInstrumentGuardField* pCombInstrumentGuard, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryCombInstrumentGuard(m_rust, pCombInstrumentGuard, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryCombAction(CThostFtdcCombActionField* pCombAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryCombAction(m_rust, pCombAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTransferSerial(CThostFtdcTransferSerialField* pTransferSerial, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTransferSerial(m_rust, pTransferSerial, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryAccountregister(CThostFtdcAccountregisterField* pAccountregister, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryAccountregister(m_rust, pAccountregister, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspError(CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspError(m_rust, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRtnOrder(CThostFtdcOrderField* pOrder) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnOrder(m_rust, pOrder); }
void Rust_CThostFtdcTraderSpi::OnRtnTrade(CThostFtdcTradeField* pTrade) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnTrade(m_rust, pTrade); }
void Rust_CThostFtdcTraderSpi::OnErrRtnOrderInsert(CThostFtdcInputOrderField* pInputOrder, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnOrderInsert(m_rust, pInputOrder, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnOrderAction(CThostFtdcOrderActionField* pOrderAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnOrderAction(m_rust, pOrderAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnInstrumentStatus(CThostFtdcInstrumentStatusField* pInstrumentStatus) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnInstrumentStatus(m_rust, pInstrumentStatus); }
void Rust_CThostFtdcTraderSpi::OnRtnBulletin(CThostFtdcBulletinField* pBulletin) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnBulletin(m_rust, pBulletin); }
void Rust_CThostFtdcTraderSpi::OnRtnTradingNotice(CThostFtdcTradingNoticeInfoField* pTradingNoticeInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnTradingNotice(m_rust, pTradingNoticeInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnErrorConditionalOrder(CThostFtdcErrorConditionalOrderField* pErrorConditionalOrder) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnErrorConditionalOrder(m_rust, pErrorConditionalOrder); }
void Rust_CThostFtdcTraderSpi::OnRtnExecOrder(CThostFtdcExecOrderField* pExecOrder) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnExecOrder(m_rust, pExecOrder); }
void Rust_CThostFtdcTraderSpi::OnErrRtnExecOrderInsert(CThostFtdcInputExecOrderField* pInputExecOrder, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnExecOrderInsert(m_rust, pInputExecOrder, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnExecOrderAction(CThostFtdcExecOrderActionField* pExecOrderAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnExecOrderAction(m_rust, pExecOrderAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnForQuoteInsert(CThostFtdcInputForQuoteField* pInputForQuote, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnForQuoteInsert(m_rust, pInputForQuote, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnQuote(CThostFtdcQuoteField* pQuote) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnQuote(m_rust, pQuote); }
void Rust_CThostFtdcTraderSpi::OnErrRtnQuoteInsert(CThostFtdcInputQuoteField* pInputQuote, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnQuoteInsert(m_rust, pInputQuote, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnQuoteAction(CThostFtdcQuoteActionField* pQuoteAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnQuoteAction(m_rust, pQuoteAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnForQuoteRsp(CThostFtdcForQuoteRspField* pForQuoteRsp) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnForQuoteRsp(m_rust, pForQuoteRsp); }
void Rust_CThostFtdcTraderSpi::OnRtnCFMMCTradingAccountToken(CThostFtdcCFMMCTradingAccountTokenField* pCFMMCTradingAccountToken) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnCFMMCTradingAccountToken(m_rust, pCFMMCTradingAccountToken); }
void Rust_CThostFtdcTraderSpi::OnErrRtnBatchOrderAction(CThostFtdcBatchOrderActionField* pBatchOrderAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnBatchOrderAction(m_rust, pBatchOrderAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnOptionSelfClose(CThostFtdcOptionSelfCloseField* pOptionSelfClose) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnOptionSelfClose(m_rust, pOptionSelfClose); }
void Rust_CThostFtdcTraderSpi::OnErrRtnOptionSelfCloseInsert(CThostFtdcInputOptionSelfCloseField* pInputOptionSelfClose, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnOptionSelfCloseInsert(m_rust, pInputOptionSelfClose, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnOptionSelfCloseAction(CThostFtdcOptionSelfCloseActionField* pOptionSelfCloseAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnOptionSelfCloseAction(m_rust, pOptionSelfCloseAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnCombAction(CThostFtdcCombActionField* pCombAction) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnCombAction(m_rust, pCombAction); }
void Rust_CThostFtdcTraderSpi::OnErrRtnCombActionInsert(CThostFtdcInputCombActionField* pInputCombAction, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnCombActionInsert(m_rust, pInputCombAction, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRspQryContractBank(CThostFtdcContractBankField* pContractBank, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryContractBank(m_rust, pContractBank, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryParkedOrder(CThostFtdcParkedOrderField* pParkedOrder, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryParkedOrder(m_rust, pParkedOrder, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryParkedOrderAction(CThostFtdcParkedOrderActionField* pParkedOrderAction, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryParkedOrderAction(m_rust, pParkedOrderAction, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryTradingNotice(CThostFtdcTradingNoticeField* pTradingNotice, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryTradingNotice(m_rust, pTradingNotice, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryBrokerTradingParams(CThostFtdcBrokerTradingParamsField* pBrokerTradingParams, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryBrokerTradingParams(m_rust, pBrokerTradingParams, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQryBrokerTradingAlgos(CThostFtdcBrokerTradingAlgosField* pBrokerTradingAlgos, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQryBrokerTradingAlgos(m_rust, pBrokerTradingAlgos, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQueryCFMMCTradingAccountToken(CThostFtdcQueryCFMMCTradingAccountTokenField* pQueryCFMMCTradingAccountToken, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQueryCFMMCTradingAccountToken(m_rust, pQueryCFMMCTradingAccountToken, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRtnFromBankToFutureByBank(CThostFtdcRspTransferField* pRspTransfer) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnFromBankToFutureByBank(m_rust, pRspTransfer); }
void Rust_CThostFtdcTraderSpi::OnRtnFromFutureToBankByBank(CThostFtdcRspTransferField* pRspTransfer) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnFromFutureToBankByBank(m_rust, pRspTransfer); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByBank(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromBankToFutureByBank(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByBank(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromFutureToBankByBank(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRtnFromBankToFutureByFuture(CThostFtdcRspTransferField* pRspTransfer) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnFromBankToFutureByFuture(m_rust, pRspTransfer); }
void Rust_CThostFtdcTraderSpi::OnRtnFromFutureToBankByFuture(CThostFtdcRspTransferField* pRspTransfer) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnFromFutureToBankByFuture(m_rust, pRspTransfer); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByFutureManual(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromBankToFutureByFutureManual(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByFutureManual(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromFutureToBankByFutureManual(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRtnQueryBankBalanceByFuture(CThostFtdcNotifyQueryAccountField* pNotifyQueryAccount) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnQueryBankBalanceByFuture(m_rust, pNotifyQueryAccount); }
void Rust_CThostFtdcTraderSpi::OnErrRtnBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnBankToFutureByFuture(m_rust, pReqTransfer, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnFutureToBankByFuture(m_rust, pReqTransfer, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnRepealBankToFutureByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnRepealBankToFutureByFutureManual(m_rust, pReqRepeal, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnRepealFutureToBankByFutureManual(CThostFtdcReqRepealField* pReqRepeal, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnRepealFutureToBankByFutureManual(m_rust, pReqRepeal, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnErrRtnQueryBankBalanceByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo) { return Rust_CThostFtdcTraderSpi_Trait_OnErrRtnQueryBankBalanceByFuture(m_rust, pReqQueryAccount, pRspInfo); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromBankToFutureByFuture(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromBankToFutureByFuture(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRtnRepealFromFutureToBankByFuture(CThostFtdcRspRepealField* pRspRepeal) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnRepealFromFutureToBankByFuture(m_rust, pRspRepeal); }
void Rust_CThostFtdcTraderSpi::OnRspFromBankToFutureByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspFromBankToFutureByFuture(m_rust, pReqTransfer, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspFromFutureToBankByFuture(CThostFtdcReqTransferField* pReqTransfer, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspFromFutureToBankByFuture(m_rust, pReqTransfer, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRspQueryBankAccountMoneyByFuture(CThostFtdcReqQueryAccountField* pReqQueryAccount, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcTraderSpi_Trait_OnRspQueryBankAccountMoneyByFuture(m_rust, pReqQueryAccount, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcTraderSpi::OnRtnOpenAccountByBank(CThostFtdcOpenAccountField* pOpenAccount) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnOpenAccountByBank(m_rust, pOpenAccount); }
void Rust_CThostFtdcTraderSpi::OnRtnCancelAccountByBank(CThostFtdcCancelAccountField* pCancelAccount) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnCancelAccountByBank(m_rust, pCancelAccount); }
void Rust_CThostFtdcTraderSpi::OnRtnChangeAccountByBank(CThostFtdcChangeAccountField* pChangeAccount) { return Rust_CThostFtdcTraderSpi_Trait_OnRtnChangeAccountByBank(m_rust, pChangeAccount); }
Rust_CThostFtdcTraderSpi::Rust_CThostFtdcTraderSpi(void *rust) : m_rust(rust) {}
Rust_CThostFtdcTraderSpi::~Rust_CThostFtdcTraderSpi() { Rust_CThostFtdcTraderSpi_Trait_Drop(m_rust); }

Rust_CThostFtdcMdApi::Rust_CThostFtdcMdApi(CThostFtdcMdApi *member) : m_member(member) {  };
Rust_CThostFtdcMdApi::~Rust_CThostFtdcMdApi() {  };
void Rust_CThostFtdcMdApi::Release() { return m_member->Release(); }
void Rust_CThostFtdcMdApi::Init() { return m_member->Init(); }
int Rust_CThostFtdcMdApi::Join() { return m_member->Join(); }
const char* Rust_CThostFtdcMdApi::GetTradingDay() { return m_member->GetTradingDay(); }
void Rust_CThostFtdcMdApi::RegisterFront(char* pszFrontAddress) { return m_member->RegisterFront(pszFrontAddress); }
void Rust_CThostFtdcMdApi::RegisterNameServer(char* pszNsAddress) { return m_member->RegisterNameServer(pszNsAddress); }
void Rust_CThostFtdcMdApi::RegisterFensUserInfo(CThostFtdcFensUserInfoField * pFensUserInfo) { return m_member->RegisterFensUserInfo(pFensUserInfo); }
void Rust_CThostFtdcMdApi::RegisterSpi(CThostFtdcMdSpi* pSpi) { return m_member->RegisterSpi(pSpi); }
int Rust_CThostFtdcMdApi::SubscribeMarketData(char* ppInstrumentID[], int nCount) { return m_member->SubscribeMarketData(ppInstrumentID, nCount); }
int Rust_CThostFtdcMdApi::UnSubscribeMarketData(char* ppInstrumentID[], int nCount) { return m_member->UnSubscribeMarketData(ppInstrumentID, nCount); }
int Rust_CThostFtdcMdApi::SubscribeForQuoteRsp(char* ppInstrumentID[], int nCount) { return m_member->SubscribeForQuoteRsp(ppInstrumentID, nCount); }
int Rust_CThostFtdcMdApi::UnSubscribeForQuoteRsp(char* ppInstrumentID[], int nCount) { return m_member->UnSubscribeForQuoteRsp(ppInstrumentID, nCount); }
int Rust_CThostFtdcMdApi::ReqUserLogin(CThostFtdcReqUserLoginField* pReqUserLoginField, int nRequestID) { return m_member->ReqUserLogin(pReqUserLoginField, nRequestID); }
int Rust_CThostFtdcMdApi::ReqUserLogout(CThostFtdcUserLogoutField* pUserLogout, int nRequestID) { return m_member->ReqUserLogout(pUserLogout, nRequestID); }

void Rust_CThostFtdcMdSpi::OnFrontConnected() { return Rust_CThostFtdcMdSpi_Trait_OnFrontConnected(m_rust); }
void Rust_CThostFtdcMdSpi::OnFrontDisconnected(int nReason) { return Rust_CThostFtdcMdSpi_Trait_OnFrontDisconnected(m_rust, nReason); }
void Rust_CThostFtdcMdSpi::OnHeartBeatWarning(int nTimeLapse) { return Rust_CThostFtdcMdSpi_Trait_OnHeartBeatWarning(m_rust, nTimeLapse); }
void Rust_CThostFtdcMdSpi::OnRspUserLogin(CThostFtdcRspUserLoginField* pRspUserLogin, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspUserLogin(m_rust, pRspUserLogin, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspUserLogout(CThostFtdcUserLogoutField* pUserLogout, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspUserLogout(m_rust, pUserLogout, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspError(CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspError(m_rust, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspSubMarketData(CThostFtdcSpecificInstrumentField* pSpecificInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspSubMarketData(m_rust, pSpecificInstrument, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspUnSubMarketData(CThostFtdcSpecificInstrumentField* pSpecificInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspUnSubMarketData(m_rust, pSpecificInstrument, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspSubForQuoteRsp(CThostFtdcSpecificInstrumentField* pSpecificInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspSubForQuoteRsp(m_rust, pSpecificInstrument, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRspUnSubForQuoteRsp(CThostFtdcSpecificInstrumentField* pSpecificInstrument, CThostFtdcRspInfoField* pRspInfo, int nRequestID, bool bIsLast) { return Rust_CThostFtdcMdSpi_Trait_OnRspUnSubForQuoteRsp(m_rust, pSpecificInstrument, pRspInfo, nRequestID, bIsLast); }
void Rust_CThostFtdcMdSpi::OnRtnDepthMarketData(CThostFtdcDepthMarketDataField* pDepthMarketData) { return Rust_CThostFtdcMdSpi_Trait_OnRtnDepthMarketData(m_rust, pDepthMarketData); }
void Rust_CThostFtdcMdSpi::OnRtnForQuoteRsp(CThostFtdcForQuoteRspField* pForQuoteRsp) { return Rust_CThostFtdcMdSpi_Trait_OnRtnForQuoteRsp(m_rust, pForQuoteRsp); }
Rust_CThostFtdcMdSpi::Rust_CThostFtdcMdSpi(void *rust) : m_rust(rust) {}
Rust_CThostFtdcMdSpi::~Rust_CThostFtdcMdSpi() { Rust_CThostFtdcMdSpi_Trait_Drop(m_rust); }

